# Generated by Django 2.0.4 on 2018-04-27 11:09

from django.db import migrations, models
import django.utils.timezone

import string
import random


def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


def create_category_slug(apps, schema_editor):
    # We can't import the Category model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("bike_management", "Category")
    for category in Category.objects.all():
        category.slug = id_generator()
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bike_management', '0003_auto_20180427_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=255, unique=True, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(create_category_slug)
    ]
